/**
 * TypeScript Type Definitions
 * Supabase tabloları için TypeScript interface tanımlamaları
 */

/**
 * newsletter_subscribers Tablosu
 * 
 * SQL Schema:
 * create table public.newsletter_subscribers (
 *   id bigint generated by default as identity primary key,
 *   email text not null unique,
 *   is_active boolean default true,
 *   created_at timestamp with time zone default timezone('utc'::text, now()) not null
 * );
 */
export interface NewsletterSubscriber {
  id: number; // bigint -> number
  email: string; // text
  is_active: boolean; // boolean, default true
  created_at: string; // timestamp with time zone -> ISO string
}

/**
 * Supabase'den dönen veri formatı (insert/update için)
 */
export interface NewsletterSubscriberInsert {
  email: string;
  is_active?: boolean; // Optional, default true
}

/**
 * Supabase'den dönen veri formatı (update için)
 */
export interface NewsletterSubscriberUpdate {
  email?: string;
  is_active?: boolean;
}
